version: '3.7'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inca-api
    ports:
      - "9050:9050"
    volumes:
      - .:/app
    depends_on:
      - minio